/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.SqlContext;
import Controller.SqlController;
import Model.Vehicle;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hoang
 */
public final class FormQuanLyPT extends javax.swing.JFrame {
    private ArrayList<Vehicle> list;
    DefaultTableModel model;
    Connection conn;
    SqlController sqlController;
    /**
     * Creates new form FormQuanLyPT
     * @throws java.sql.SQLException
     */
    public FormQuanLyPT() throws SQLException {
        initComponents();
        conn = SqlContext.getConn();
        sqlController = new SqlController();
        this.setLocationRelativeTo(null);
        list = sqlController.findAll();
        model = (DefaultTableModel) tbl_TrangChu.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Mã Phương tiện","Tên phương tiện","Hãng sản xuất","Loại phương tiện","Năm sản xuất","Giá","Màu","Số ghế ngồi","Loại động cơ","Công suất","Trọng tải"
        });
        showTable();
    }
    
    public void showTable(){
        for(Vehicle v:list){
            model.addRow(new Object[]{
                v.getVehicleId(),v.getVehicleName(),v.getMaker(),v.getVehType(),v.getYear(),v.getUnitPrice(),v.getColor(),v.getSeatNum(),v.getEngineType(),v.getWattage(),v.getTonnage()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        btn_QuanLyXeMay = new javax.swing.JButton();
        btn_QuanLyOTo = new javax.swing.JButton();
        btn_QuanLyXeTai = new javax.swing.JButton();
        btn_QuanLyTaiKhoan = new javax.swing.JButton();
        txt_TimKiem = new javax.swing.JTextField();
        btn_TimKiem = new javax.swing.JButton();
        btn_dangxuat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_TrangChu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("QUẢN LÝ PHƯƠNG TIỆN");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Họ tên:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Loại tài khoản:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_QuanLyXeMay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_QuanLyXeMay.setText("Quản lý xe máy");
        btn_QuanLyXeMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyXeMayActionPerformed(evt);
            }
        });

        btn_QuanLyOTo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_QuanLyOTo.setText("Quản lý ô tô");
        btn_QuanLyOTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyOToActionPerformed(evt);
            }
        });

        btn_QuanLyXeTai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_QuanLyXeTai.setText("Quản lý xe tải");
        btn_QuanLyXeTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyXeTaiActionPerformed(evt);
            }
        });

        btn_QuanLyTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_QuanLyTaiKhoan.setText("Quản lý tài khoản");
        btn_QuanLyTaiKhoan.setToolTipText("");
        btn_QuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyTaiKhoanActionPerformed(evt);
            }
        });

        txt_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TimKiemActionPerformed(evt);
            }
        });

        btn_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_TimKiem.setText("Tìm Kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        btn_dangxuat.setText("Đăng xuất");
        btn_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_TimKiem))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_QuanLyXeMay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btn_QuanLyOTo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btn_QuanLyXeTai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btn_QuanLyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_TimKiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_QuanLyXeMay)
                            .addComponent(btn_QuanLyOTo)
                            .addComponent(btn_QuanLyTaiKhoan)
                            .addComponent(btn_QuanLyXeTai))
                        .addGap(25, 25, 25))))
        );

        jScrollPane2.setToolTipText("");

        tbl_TrangChu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phương tiện", "Tên phương tiện", "Hãng sản xuất", "Loại phương tiện", "Năm sản xuất", "Giá", "Màu", "Số ghế ngồi", "Loại động cơ", "Công suất", "Trọng tải"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_TrangChu);
        if (tbl_TrangChu.getColumnModel().getColumnCount() > 0) {
            tbl_TrangChu.getColumnModel().getColumn(0).setHeaderValue("Mã phương tiện");
            tbl_TrangChu.getColumnModel().getColumn(1).setHeaderValue("Tên phương tiện");
            tbl_TrangChu.getColumnModel().getColumn(2).setHeaderValue("Hãng sản xuất");
            tbl_TrangChu.getColumnModel().getColumn(3).setHeaderValue("Loại phương tiện");
            tbl_TrangChu.getColumnModel().getColumn(4).setHeaderValue("Năm sản xuất");
            tbl_TrangChu.getColumnModel().getColumn(5).setHeaderValue("Giá");
            tbl_TrangChu.getColumnModel().getColumn(6).setHeaderValue("Màu");
            tbl_TrangChu.getColumnModel().getColumn(7).setHeaderValue("Số ghế ngồi");
            tbl_TrangChu.getColumnModel().getColumn(8).setHeaderValue("Loại động cơ");
            tbl_TrangChu.getColumnModel().getColumn(9).setHeaderValue("Công suất");
            tbl_TrangChu.getColumnModel().getColumn(10).setHeaderValue("Trọng tải");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(631, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(363, 363, 363))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_QuanLyXeMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyXeMayActionPerformed
        QuanLyXeMayUI qlxm;
        try {
            qlxm = new QuanLyXeMayUI();
            qlxm.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FormQuanLyPT.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_QuanLyXeMayActionPerformed

    private void btn_QuanLyOToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyOToActionPerformed
        QuanLyOToUI qloto;
        try {
            qloto = new QuanLyOToUI();
            qloto.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FormQuanLyPT.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btn_QuanLyOToActionPerformed

    private void btn_QuanLyXeTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyXeTaiActionPerformed
        QuanLyXeTaiUI qlxt = new QuanLyXeTaiUI();
        qlxt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_QuanLyXeTaiActionPerformed

    private void btn_QuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyTaiKhoanActionPerformed
        QuanLyTaiKhoanUI qltk = new QuanLyTaiKhoanUI();
        qltk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_QuanLyTaiKhoanActionPerformed

    private void txt_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TimKiemActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        if(txt_TimKiem.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Mã phương tiện không được để trống!");
            return;
        }
        
        try{
            Vehicle v = sqlController.findById(txt_TimKiem.getText());
            List<Vehicle> listVehicle = new ArrayList<>();
            listVehicle.add(v);
            showData(listVehicle);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Phương tiện không tìm thấy !");
        }
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed

        int dx = JOptionPane.showConfirmDialog(null,"Bạn có muốn đăng xuất?", "Đăng xuất !!!",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
        if(dx == JOptionPane.YES_OPTION){
            DangNhapUI dn;
            dn = new DangNhapUI(new SqlController());
            dn.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_dangxuatActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new FormQuanLyPT().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(FormQuanLyPT.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    
    public void showData(List<Vehicle> vehiclel){
        List<Vehicle> listVehicle = new ArrayList<>();
        listVehicle = vehiclel;
        DefaultTableModel tableModel;
        tbl_TrangChu.getModel();
        tableModel=(DefaultTableModel)tbl_TrangChu.getModel();
        tableModel.setRowCount(0);
        listVehicle.forEach((vehicle)->{
            tableModel.addRow(new Object[]{
                vehicle.getVehicleId(),vehicle.getVehicleName(),vehicle.getMaker(),vehicle.getUnitPrice(),vehicle.getYear(),vehicle.getColor(),vehicle.getSeatNum(),vehicle.getEngineType(),vehicle.getWattage(),vehicle.getTonnage()
            });
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_QuanLyOTo;
    private javax.swing.JButton btn_QuanLyTaiKhoan;
    private javax.swing.JButton btn_QuanLyXeMay;
    private javax.swing.JButton btn_QuanLyXeTai;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tbl_TrangChu;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
